# Generated by Django 5.2 on 2025-04-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('operation_type', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('arrendamiento', 'Arrendamiento')], max_length=20, verbose_name='Tipo de operación')),
                ('property_type', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('oficina', 'Oficina'), ('local', 'Local Comercial'), ('terreno', 'Terreno'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('estudio', 'Estudio')], max_length=20, verbose_name='Tipo de propiedad')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Habitaciones')),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baños')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área (m²)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Imagen destacada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
    ]
