# Generated by Django 5.2 on 2025-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.PositiveIntegerField(help_text='Area in square meters'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='operation_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Lease', 'Lease')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial'), ('Land', 'Land')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
